language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t albertojnk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true albertojnk/docker-react npm run test